[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]

[[redirects]]
  from = "/api/download"
  to = "/.netlify/functions/download"
  status = 200
  force = true

[[redirects]]
  from = "/api/proxy"
  to = "/.netlify/functions/proxy"
  status = 200
  force = true

[[redirects]]
  from = "/api/download-file"
  to = "/.netlify/functions/download-file"
  status = 200
  force = true

[[redirects]]
  from = "/api/proxy-image"
  to = "/.netlify/functions/proxy-image"
  status = 200
  force = true
